version: 0.2

phases:
  build:
    commands:
      - python3.6 handler/pytest.py handler/test_handler.py
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
