AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Resources:
  QADB:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: linkstat
      Engine: aurora
      MasterUsername: !Ref DB_USERNAME
      MasterUserPassword: !Ref DB_PASSWORD
  RDSDBInstance1:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora
      DBClusterIdentifier:
        Ref: QADB
  Flask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler/index.app
      Runtime: python3.6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        TestEvent:
          Type: Api
          Properties:
            Path: /test
            Method: post
        TwilioSMSMOEvent:
          Type: Api
          Properties:
            Path: /twilio/sms/mo
            Method: post
